### ISSUE TITLE
setupFilesAfterEnv index.js not found

### ISSUE THREAD

**Issue by MicMonen** [danielbayley/jest-preset-coffeescript#12]
After upgrading to newest version my test breaks because jest is looking inside the rootDir for the setupFilesAfterEnv index.js file. If I point the setting to the correct directory (node_modules/jest-preset-coffeescript/index.js), it works.

Is it possible to make this path dynamic?

**Comment by ivands** [comment]
Ye the update gave me this error as well.
The setupFilesAfterEnv path is not working.
Please fix it!

Great work btw.

**Comment by danielbayley** [comment]
@MicMonen @ivands Should be fixed now; please test… thanks! 👍

**Comment by MicMonen** [comment]
Thanks and can confirm it working now!
