### ISSUE TITLE
Preset jest-preset-coffeescript is invalid

### ISSUE THREAD

**Issue by ovikholt** [danielbayley/jest-preset-coffeescript#34]
Is this package not maintained anymore?  I absolutely LOVE coffeescript and will do whatever it takes to be able to continue using it.

I'm trying to deploy an app to Google Cloud Build, but I'm getting the following error:

```
> npx env-cmd npx jest --runInBand

npx: installed 8 in 2.173s
npx: installed 486 in 21.768s
● Validation Error:

  Preset jest-preset-coffeescript is invalid:

  The "id" argument must be of type string. Received type object
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:632:3)
    at require (internal/modules/cjs/helpers.js:22:18)
    at setupPreset (/root/.npm/_npx/56/lib/node_modules/jest/node_modules/jest-config/build/normalize.js:298:14)
    at normalize (/root/.npm/_npx/56/lib/node_modules/jest/node_modules/jest-config/build/normalize.js:643:15)
    at readConfig (/root/.npm/_npx/56/lib/node_modules/jest/node_modules/jest-config/build/index.js:220:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

```

You don't suppose you could help me figuring this one out?

**Comment by ovikholt** [comment]
It seems to be relevant that I'm using the npm package package-yaml. Because, when I copy the generated package.json into my docker image, and avoid .gitignoring it, everything works. But when I try to let package.json be generated automatically *inside* the docker image, the above error occurs.

**Comment by ovikholt** [comment]
I got it to work. Not sure how.

**Comment by danielbayley** [comment]
> Is this package not maintained anymore?

Sorry, yes it is… Iv‘e been messed around for months by RSA insurance, on a claim for display damage on my old MacBook Pro, followed by 2 ebay sellers, in my attempts to buy a replacement machine. I finally went and paid cash for this replacement just before the current pandemic mess. But out of the box, I have so much setup to do just to get back to where I was. All of which has obviously set me back… but I will be updating this project (PRs welcome). @ovikholt Did you figure out if this error was actually caused by your setup in the end?

> I absolutely LOVE coffeescript and will do whatever it takes to be able to continue using it.

Me too!

**Comment by danielbayley** [comment]
@ovikholt Also see #35… I just released an update. So please test and let me know if this issue is fixed 👍

**Comment by jaredmoody** [comment]
I am also seeing this same error message on `master`

**Comment by danielbayley** [comment]
> I got it to work. Not sure how.

@jaredmoody @ovikholt Did you get to the bottom of this?

**Comment by ovikholt** [comment]
Daniel, hi! I understand you had a lot to do with your new machine. Glad it went well.

I'm sorry! I don't know what I did here to solve it. It's quite a while ago now ... :/ 
I'll keep this issue in mind though, in case I manage to produce the error again.

Thanks for maintaining ^_^ @danielbayley

**Comment by jaredmoody** [comment]
@danielbayley no, I did not get this working on master

**Comment by danielbayley** [comment]
> I did not get this working on master

@jaredmoody @ovikholt See https://github.com/danielbayley/jest-preset-coffeescript/issues/46#issuecomment-710344380
