### ISSUE TITLE
Bad setupFilesAfterEnv path

### ISSUE THREAD

**Issue by gquittet** [danielbayley/jest-preset-coffeescript#44]
When I run Jest on my project, I got this error:

```
● Validation Error:

  Module /Users/Dan/Work/dev/npm/jest-preset-coffeescript in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/me/Projects/coffeescript/nameOfMyProject
```

I've investigate, and you'll generate a JSON file on your machine with `__dirname`. The problem is that it will use your path and it will work on your machine but not on other machines.

```json
{
  "moduleFileExtensions": [
    "js",
    "json",
    "coffee",
    "litcoffee",
    "coffee.md"
  ],
  "testRegex": ".*(test|spec).*\\.(coffee|litcoffee|coffee.md)$",
  "testPathIgnorePatterns": [
    "node_modules",
    "fixtures"
  ],
  "transform": {
    "coffee|litcoffee|coffee.md": "jest-preset-coffeescript"
  },
  "mapCoverage": true,
  "setupFilesAfterEnv": [
    "/Users/Dan/Work/dev/npm/jest-preset-coffeescript"
  ]
}
```

If this issue take to you too much time, I can make a PR.

**Comment by jacekk** [comment]
I have to confirm @gquittet 's report.

This change https://github.com/danielbayley/jest-preset-coffeescript/commit/bb976cc17a9f7f5165811b1af106204beb785d4b caused **"/Users/Dan/Work/dev/npm/jest-preset-coffeescript"** to be present in 
https://unpkg.com/jest-preset-coffeescript@1.2.0/jest-preset.json . Definitely not a "Fix setupFilesAfterEnv" :thinking:

**Comment by danielbayley** [comment]
@gquittet @jacekk Yeah sorry, it was a rushed "fix"… I quickly realised the error, but actually, a seemingly minor upstream change in Jest has forced me to have to take a different approach with this package. However I have almost rewritten it already, so will publish an update soon 👍
