### ISSUE TITLE
Project "package.json" file is overwritten while running "test"

### ISSUE THREAD

**Issue by jacekk** [danielbayley/jest-preset-coffeescript#45]
After migration from **1.1.1** to **1.3.0**, running `test` task causes the project very `package.json` file to be overwritten by sth that `jest-preset-coffeescript` seems to be generating after last changes. Probably this one: https://github.com/danielbayley/jest-preset-coffeescript/commit/b1dbe4f2f52bf38c3409d2dbd75a5b3b0e0d9de9 . Especially line 14 of `jest-preset.coffee`, where I can see `fs.writeFileSync` and `package.json` as the target file. I really doubt this is the expected behavior :thinking: 

Repo and branches comparison that reproduce the above issue: https://github.com/jacekk/jest-preset-coffeescript-override-issue-reproduce/compare/issue/jest-preset-coffeescript-1-3-0?expand=1

**Comment by danielbayley** [comment]
@jacekk See https://github.com/danielbayley/jest-preset-coffeescript/issues/46#issuecomment-616205013 …

**Comment by rposborne** [comment]
@danielbayley Not sure how #46 addesses this issue.  It looks the file is using a relative path when loading the package json ( relative to `jest-preset.cofffee` but is writing to `package.json` which is unscoped and will write to the location where the node process originated from.  

Long story short.  https://github.com/danielbayley/jest-preset-coffeescript/blob/master/jest-preset.coffee#L14  will overwrite a projects `package.json` file.   I would be happy to submit a PR but it is not clear why this code is here.
